<a href="https://colab.research.google.com/github/Mikolajkunka/Missp/blob/main/cd_podstaw_pythona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat") 
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [ ]:
print(a_list+b_list) #suma list
print(n_array+n_array) #suma wektorów

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [ ]:
a_list[3]

4

In [ ]:
a_list.append(100) # dodaje element na końcu listy
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100]


In [ ]:
tekst = "tekst"
nowy_tekst = tekst + "jakiś inny"
print(nowy_tekst)

tekstjakiś inny


In [ ]:
k_krotka[4]

5

In [ ]:
k_krotka[5].append(1)
print(k_krotka)

(1, 2, 3, 4, 5, [1, 2, 3, 1], 'temat')


In [ ]:
k_krotka.append(100)

AttributeError: ignored

In [ ]:
suma = np.array(b_list)+np.array(b_list)

suma.dtype



dtype('int64')

In [ ]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [ ]:
n_array = np.array(a_list) # wektor numpy

In [ ]:
n_array

array([1, 2, 3, 4, 5])

In [ ]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"} #klucz i wartość pod value dowolny obiekt a pod kluczem coś haszowanego(ten sam obiekt, kluczem nie może być lista)

In [ ]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [ ]:
studenci_slownik["Zosia"]

22

In [ ]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [ ]:
for elementy in studenci_slownik.items(): #do uzyskania kluczy i wartości
    print(elementy)

(123, 123)
('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])
((1, 2), 'Krotka')


In [ ]:
for imie, ocena in studenci_slownik.items():
    print("{} ma ocene {}".format(imie,ocena))

123 ma ocene 123
Igor ma ocene 3
Frankek ma ocene 5
Zosia ma ocene 22
Julia ma ocene [2, 21]
(1, 2) ma ocene Krotka


In [ ]:
for elementy in studenci_slownik.values(): #do uzyskania kluczy i wartości
    print(elementy)

123
3
5
22
[2, 21]
Krotka


In [ ]:
studenci_slownik["Cuthulu"]= -1000000

In [ ]:
studenci_slownik

{(1, 2): 'Krotka',
 123: 123,
 'Cuthulu': -1000000,
 'Frankek': 5,
 'Igor': 3,
 'Julia': [2, 21],
 'Zosia': 22}

In [ ]:
stara_lista = ["Mikolaj", "Andrzej", "nie imie", "Zofia"]
nowa_lista = [imie for imie in stara_lista if imie[0].isupper()]
print(nowa_lista)

['Mikolaj', 'Andrzej', 'Zofia']


In [ ]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

automatyczna_lista_pary=[(liczba,liczba**2) for liczba in range(100) if liczba%4==0]

print(automatyczna_lista_pary)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]
[(0, 0), (4, 16), (8, 64), (12, 144), (16, 256), (20, 400), (24, 576), (28, 784), (32, 1024), (36, 1296), (40, 1600), (44, 1936), (48, 2304), (52, 2704), (56, 3136), (60, 3600), (64, 4096), (68, 4624), (72, 5184), (76, 5776), (80, 6400), (84, 7056), (88, 7744), (92, 8464), (96, 9216)]


In [ ]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 123, 1: 'Igor', 2: 'Frankek', 3: 'Zosia', 4: 'Julia', 5: (1, 2), 6: 'Cuthulu'}


In [ ]:
print(studenci_slownik)

print("Igor" in studenci_slownik) # w słownikach szybciej sprawdzamy czy wustepuje jakis element niz w przypadku listy

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka', 'Cuthulu': -1000000}
True


In [ ]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [ ]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [ ]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [ ]:
1 in a
"Igor" in studenci_slownik

True

In [ ]:
studenci_lista = ["Igor_"+str(nr) for nr in range(1000)]
print(studenci_lista)
studenci_set = set(studenci_lista) #zbior z listy
print(studenci_set)

powtarzajaca_lista = ["Igor" for el in range(1000)]
print(powtarzajaca_lista)
print(set(powtarzajaca_lista))

['Igor_0', 'Igor_1', 'Igor_2', 'Igor_3', 'Igor_4', 'Igor_5', 'Igor_6', 'Igor_7', 'Igor_8', 'Igor_9', 'Igor_10', 'Igor_11', 'Igor_12', 'Igor_13', 'Igor_14', 'Igor_15', 'Igor_16', 'Igor_17', 'Igor_18', 'Igor_19', 'Igor_20', 'Igor_21', 'Igor_22', 'Igor_23', 'Igor_24', 'Igor_25', 'Igor_26', 'Igor_27', 'Igor_28', 'Igor_29', 'Igor_30', 'Igor_31', 'Igor_32', 'Igor_33', 'Igor_34', 'Igor_35', 'Igor_36', 'Igor_37', 'Igor_38', 'Igor_39', 'Igor_40', 'Igor_41', 'Igor_42', 'Igor_43', 'Igor_44', 'Igor_45', 'Igor_46', 'Igor_47', 'Igor_48', 'Igor_49', 'Igor_50', 'Igor_51', 'Igor_52', 'Igor_53', 'Igor_54', 'Igor_55', 'Igor_56', 'Igor_57', 'Igor_58', 'Igor_59', 'Igor_60', 'Igor_61', 'Igor_62', 'Igor_63', 'Igor_64', 'Igor_65', 'Igor_66', 'Igor_67', 'Igor_68', 'Igor_69', 'Igor_70', 'Igor_71', 'Igor_72', 'Igor_73', 'Igor_74', 'Igor_75', 'Igor_76', 'Igor_77', 'Igor_78', 'Igor_79', 'Igor_80', 'Igor_81', 'Igor_82', 'Igor_83', 'Igor_84', 'Igor_85', 'Igor_86', 'Igor_87', 'Igor_88', 'Igor_89', 'Igor_90', 'Igor_91

In [ ]:
%%timeit

##udowadniamy ze przeszukiwanie set jest szybsze niz listy
jest = "Igor_999" in studenci_lista

100000 loops, best of 3: 14.8 µs per loop


In [ ]:
%%timeit

##udowadniamy ze przeszukiwanie set jest szybsze niz listy
jest = "Igor_999" in studenci_set

The slowest run took 42.76 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 41.9 ns per loop


### Własne typy

In [ ]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [ ]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [ ]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [ ]:
pio_zajecia.ile_zajec

4

In [ ]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [ ]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [ ]:
pio_zajecia.lista_zajec.append("MISP")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia.ile_mispow()

4

In [ ]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'MISP']


In [ ]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, MISP

In [ ]:
print(pio_zajecia.ile_zajec)

5


In [ ]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [ ]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [ ]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"

SyntaxError: ignored

In [ ]:
print ("Podaj numer telefonu!")
wprowadzony_numer = input()

class Telefon:

    def __init__(self, test):
        self.numer = test
       
    @property
    def sprawdz(self):
        if (len(self.numer)==9) and self.numer[0] != 0 :
          print("Prawidłowy numer")     
        else:
          print("ERROR: numer ma złą długość")

    @property
    def wypisz(self):
      odczyt_numeru = ""
      cyfry_po_polsku = ["zero", "jeden", "dwa", "trzy", "cztery", "pięć", "sześć", "siedem", "osiem", "dziewieć"]
      for i in range(len(self.numer)):
        odczyt_numeru += cyfry_po_polsku[int(self.numer[i])] + " "
      print ("Numer słownie:", odczyt_numeru) 

    @property
    def kierunkowy(self):
        if '4' in self.numer[0]  and '2' in self.numer[1] :
          print("Województwo Łódzkie") 
        else:
          print("Województwo nieznane")

  
test = Telefon(wprowadzony_numer)
test.sprawdz
test.wypisz
test.kierunkowy






Podaj numer telefonu!
34535
ERROR: numer ma złą długość
Numer słownie: trzy cztery pięć trzy pięć 
Województwo nieznane
